image: node:18
before_script:
- corepack enable
- corepack prepare pnpm@latest-8 --activate
- pnpm config set store-dir .pnpm-store
script:
- pnpm install
- npm run build
artifacts:
paths:
    - public

