stages:
  # - test
  - deploy

workflow:
  rules:
    - if: >
        ($CI_COMMIT_REF_NAME == "main"
        || $CI_COMMIT_REF_NAME == "gh-pages")
      when: always
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: always

cache:
  paths:
    - node_modules/
    - .cache/
    - public/

# run-tests:
#   stage: test
#   image: node:18
#   before_script:
#     - corepack enable
#     - corepack prepare pnpm@latest-8 --activate
#     - pnpm config set store-dir .pnpm-store
#   script:
#     - pnpm install
#     - npm run test

pages:
  stage: deploy
  image: node:18
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-8 --activate
    - pnpm config set store-dir .pnpm-store
  script:
    - pnpm install
    - npm run build
  artifacts:
    paths:
      - public
